<?php
/**
* Implements hook_form_alter().
*/
function form_overwrite_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  /* Identify the "Add term" form for the vocabulary project */
  if ($form_id=='taxonomy_term_vocab_project_form') {
    /* Make the "Completion Months" field visible only when "Project type" is "Fixed" */
    $form['field_completion_months']['#states'] = array( 
      'visible' => array(
        ':input[name="field_project_type"]' => array('value' => 0),
      ),
    );
    /* Make the "Total Cost" field visible only when "Project type" "Fixed" is selected */
    $form['field_total_cost']['#states'] = array( 
      'visible' => array(
        ':input[name="field_project_type"]' => array('value' => 0),
      ),
    );
    /* Make the "Per Hour Rate" field visible only when "Project type" is "Hourly" */
    $form['field_per_hour_rate']['#states'] = array( 
      'visible' => array(
        ':input[name="field_project_type"]' => array('value' => 1),
      ),
    );
    /* Set the field "Per Hour Rate" required if "Project type" is "Hourly"*/
    if ($form['field_project_type']['widget']['#default_value'] == 1) {
      $form['field_per_hour_rate']['widget']['#required'] = TRUE;
      $form['field_completion_months']['widget']['#required'] = FALSE;
      $form['field_total_cost']['widget']['#required'] = FALSE;
    }
    /* Set the field "Total Cost" & "Completion Months" required if "Project type" is "Fixed" */
    else if($form['field_project_type']['widget']['#default_value'] == 0) {
      $form['field_completion_months']['widget']['#required'] = TRUE;
      $form['field_total_cost']['widget']['#required'] = TRUE;
      $form['field_per_hour_rate']['widget']['#required'] = FALSE;
    }
  }

  if($form['#id'] == "views-exposed-form-cash-inflow-view-page-1" || $form['#id'] == "views-exposed-form-cash-outflow-view-page-1") {
    //dpm($form_id);
    $form['field_ct_cashflow_date_value'] = array(
          '#type' => 'hidden',
        );

    $form['new_field_ct_cashflow_date_value'] = array(
          '#type' => 'date',
          '#title' => t('Date'),
        );
    if($form_state->getUserInput()['new_field_ct_cashflow_date_value'] != null) {
      // $form['field_ct_cashflow_date_value'] = $form_state->getUserInput()['new_field_ct_cashflow_date_value'];
      $date = $form_state->getUserInput()['new_field_ct_cashflow_date_value'];
      $date1 = date('m/d/Y', strtotime("+1 day", strtotime($date)));
      //dpm($date1);
      $form['field_ct_cashflow_date_value']['#value'] = $date1;
      //dpm($form['field_ct_cashflow_date_value']);
    }
    // $first = array_shift($form['#submit']);
    // array_unshift($form['#submit'], $first, 'date_value_submit');
  }
  if ($form['#id'] == "taxonomy-term-vocab-project-form") {
    // dpm($form);
    // dpm($form_state);
    $form['#validate'][] = 'project_term_validate';
  }
}

function project_term_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // dpm($form_state);
  // dpm($form);
  // dpm($form_state->getUserInput());

  if($form_state->getUserInput()['field_project_type'] == 0) {
    if(empty($form_state->getValue('field_total_cost')[0]['value'])) {
      $form_state->setErrorByName('field_total_cost',t("Total Cost should not be empty."));
    }
    if(empty($form_state->getValue('field_completion_months')[0]['value'])) {
      $form_state->setErrorByName('field_completion_months',t("Completion months should not be empty."));
    }
    if(!empty($form_state->getValue('field_per_hour_rate')[0]['value'])) {
      $form_state->setErrorByName('field_per_hour_rate',t("Per Hour rate must be empty in case of fixed project type"));
    }
  }
  else {
    if(!empty($form_state->getValue('field_total_cost')[0]['value'])) {
      $form_state->setErrorByName('field_total_cost',t("Total Cost must be empty in case of Hourly project type."));
    }
    if(!empty($form_state->getValue('field_completion_months')[0]['value'])) {
      $form_state->setErrorByName('field_completion_months',t("Completion months must be empty in case of Hourly project type."));
    }
    if(empty($form_state->getValue('field_per_hour_rate')[0]['value'])) {
      $form_state->setErrorByName('field_per_hour_rate',t("Per Hour rate should not be empty."));
    }
  }
}

